# Generated by Django 4.1.6 on 2023-02-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='descriptions',
            new_name='description',
        ),
    ]
